# Generated by Django 6.1 on 2026-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
